version: '3.7'

services:
  dashd:
    image: dashpay/dashd:0.17.0.0-rc2
    restart: unless-stopped
    ports: 
      - 19999:19999
    command:
      - dashd
    volumes:
      - "./dashd.conf:/dash/.dashcore/dash.conf"
  graphite:
    image: graphiteapp/graphite-statsd
    restart: always
    ports:
      - 3000:80
    volumes:
      - graphite-configs:/opt/graphite/conf
      - graphite-storage:/opt/graphite/storage
      - statsd-config:/opt/statsd/config
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    volumes:
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./blue-d.svg:/usr/share/grafana/public/img/grafana_icon.svg"
      - "grafana-storage:/var/lib/grafana"

volumes:
  grafana-storage:
  graphite-configs:
  graphite-storage:
  statsd-config:
